name: build

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Login to Nautilus Gitlab Docker Registry
        uses: docker/login-action@v2
        with:
          registry: gitlab-registry.nrp-nautilus.io
          username: ${{ secrets.GITLAB_DOCKER_REGISTRY_USER }}
          password: ${{ secrets.GITLAB_DOCKER_REGISTRY_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: |
            gitlab-registry.nrp-nautilus.io/kingb12/scarab-in-docker:latest
            kingb12/scarab-in-docker:latest
